# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4998e087c9fdf909cddad7e860d1a7e6ca0cd426f68549d85efaca6885551cbf1f6e9581852e74fd4c03e6273843dfcb1a6ddaec489200d87a2c3fda3767fa

test:
  secret_key_base: 46195e5429e3c0cf2892ae111c3d795e1c1a20c63c92245ce1ace26f25824c730feefba5ae38c54980c7e609317d0e35c073abf298eeb95169a181b8684b7247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
